version: '3'

services:

  octoprint:
    image: octoprint/octoprint:latest
    restart: always
    volumes:
      - ./data:/octoprint
      - /dev:/dev
    privileged: true

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    links:
     - octoprint
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx:/etc/nginx/

  noip:
    image: hypriot/rpi-noip
    restart: "always"
    volumes:
      - ./noip:/usr/local/etc/
