version: "3"

services: 
  noip: 
    image: hypriot/rpi-noip
    restart: always
    volumes: 
      - "./noip:/usr/local/etc/"
  octoprint: 
    image: "octoprint/octoprint:latest"
    privileged: true
    restart: always
    volumes: 
      - "./data:/octoprint"
      - "/dev:/dev"
  reverse: 
    container_name: reverse
    hostname: reverse
    image: nginx
    links: 
      - octoprint
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    volumes: 
      - "./nginx:/etc/nginx/"

